# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BotUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(869, 581)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(700, 10, 153, 104))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.BalanceLabel = QtGui.QLabel(self.frame)
        self.BalanceLabel.setObjectName(_fromUtf8("BalanceLabel"))
        self.gridLayout_2.addWidget(self.BalanceLabel, 0, 0, 1, 1)
        self.BalanceVal = QtGui.QLineEdit(self.frame)
        self.BalanceVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BalanceVal.setReadOnly(True)
        self.BalanceVal.setObjectName(_fromUtf8("BalanceVal"))
        self.gridLayout_2.addWidget(self.BalanceVal, 1, 0, 1, 1)
        self.P_LLabel = QtGui.QLabel(self.frame)
        self.P_LLabel.setObjectName(_fromUtf8("P_LLabel"))
        self.gridLayout_2.addWidget(self.P_LLabel, 2, 0, 1, 1)
        self.P_LVal = QtGui.QLineEdit(self.frame)
        self.P_LVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.P_LVal.setReadOnly(True)
        self.P_LVal.setObjectName(_fromUtf8("P_LVal"))
        self.gridLayout_2.addWidget(self.P_LVal, 3, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 681, 421))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.K_field = QtGui.QPlainTextEdit(self.frame_2)
        self.K_field.setGeometry(QtCore.QRect(140, 30, 111, 371))
        self.K_field.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.K_field.setObjectName(_fromUtf8("K_field"))
        self.D_field = QtGui.QPlainTextEdit(self.frame_2)
        self.D_field.setGeometry(QtCore.QRect(270, 30, 111, 371))
        self.D_field.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.D_field.setObjectName(_fromUtf8("D_field"))
        self.Log_field = QtGui.QPlainTextEdit(self.frame_2)
        self.Log_field.setGeometry(QtCore.QRect(400, 30, 271, 371))
        self.Log_field.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Log_field.setObjectName(_fromUtf8("Log_field"))
        self.KLabel = QtGui.QLabel(self.frame_2)
        self.KLabel.setGeometry(QtCore.QRect(140, 10, 71, 16))
        self.KLabel.setObjectName(_fromUtf8("KLabel"))
        self.DLabel = QtGui.QLabel(self.frame_2)
        self.DLabel.setGeometry(QtCore.QRect(270, 10, 71, 16))
        self.DLabel.setObjectName(_fromUtf8("DLabel"))
        self.LogLabel = QtGui.QLabel(self.frame_2)
        self.LogLabel.setGeometry(QtCore.QRect(400, 10, 46, 13))
        self.LogLabel.setObjectName(_fromUtf8("LogLabel"))
        self.Close_field = QtGui.QPlainTextEdit(self.frame_2)
        self.Close_field.setGeometry(QtCore.QRect(10, 30, 111, 371))
        self.Close_field.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Close_field.setObjectName(_fromUtf8("Close_field"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 440, 851, 93))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(-1, -1, -1, 10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.BuyButton = QtGui.QPushButton(self.widget)
        self.BuyButton.setObjectName(_fromUtf8("BuyButton"))
        self.horizontalLayout_2.addWidget(self.BuyButton)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.QuitButton = QtGui.QPushButton(self.widget)
        self.QuitButton.setObjectName(_fromUtf8("QuitButton"))
        self.horizontalLayout_2.addWidget(self.QuitButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Last = QtGui.QLabel(self.widget)
        self.Last.setObjectName(_fromUtf8("Last"))
        self.horizontalLayout.addWidget(self.Last)
        self.LastVal = QtGui.QLineEdit(self.widget)
        self.LastVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LastVal.setReadOnly(True)
        self.LastVal.setObjectName(_fromUtf8("LastVal"))
        self.horizontalLayout.addWidget(self.LastVal)
        self.Open = QtGui.QLabel(self.widget)
        self.Open.setObjectName(_fromUtf8("Open"))
        self.horizontalLayout.addWidget(self.Open)
        self.OpenVal = QtGui.QLineEdit(self.widget)
        self.OpenVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OpenVal.setReadOnly(True)
        self.OpenVal.setObjectName(_fromUtf8("OpenVal"))
        self.horizontalLayout.addWidget(self.OpenVal)
        self.Close = QtGui.QLabel(self.widget)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.horizontalLayout.addWidget(self.Close)
        self.CloseVal = QtGui.QLineEdit(self.widget)
        self.CloseVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CloseVal.setReadOnly(True)
        self.CloseVal.setObjectName(_fromUtf8("CloseVal"))
        self.horizontalLayout.addWidget(self.CloseVal)
        self.High = QtGui.QLabel(self.widget)
        self.High.setObjectName(_fromUtf8("High"))
        self.horizontalLayout.addWidget(self.High)
        self.HighVal = QtGui.QLineEdit(self.widget)
        self.HighVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HighVal.setReadOnly(True)
        self.HighVal.setObjectName(_fromUtf8("HighVal"))
        self.horizontalLayout.addWidget(self.HighVal)
        self.Low = QtGui.QLabel(self.widget)
        self.Low.setObjectName(_fromUtf8("Low"))
        self.horizontalLayout.addWidget(self.Low)
        self.LowVal = QtGui.QLineEdit(self.widget)
        self.LowVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LowVal.setReadOnly(True)
        self.LowVal.setObjectName(_fromUtf8("LowVal"))
        self.horizontalLayout.addWidget(self.LowVal)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.QuitButton.raise_()
        self.Last.raise_()
        self.LastVal.raise_()
        self.Close.raise_()
        self.Open.raise_()
        self.OpenVal.raise_()
        self.CloseVal.raise_()
        self.HighVal.raise_()
        self.LowVal.raise_()
        self.High.raise_()
        self.Low.raise_()
        self.BuyButton.raise_()
        self.pushButton_3.raise_()
        self.Close.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.BalanceLabel.setText(_translate("MainWindow", "Balance:", None))
        self.P_LLabel.setText(_translate("MainWindow", "P/L (%):", None))
        self.KLabel.setText(_translate("MainWindow", "Previous %K:", None))
        self.DLabel.setText(_translate("MainWindow", "Previous %D", None))
        self.LogLabel.setText(_translate("MainWindow", "Log:", None))
        self.label.setText(_translate("MainWindow", "Close:", None))
        self.BuyButton.setText(_translate("MainWindow", "BUY", None))
        self.pushButton_3.setText(_translate("MainWindow", "SELL", None))
        self.QuitButton.setText(_translate("MainWindow", "Quit", None))
        self.Last.setText(_translate("MainWindow", "Last:", None))
        self.Open.setText(_translate("MainWindow", "Open:", None))
        self.Close.setText(_translate("MainWindow", "Close:", None))
        self.High.setText(_translate("MainWindow", "High:", None))
        self.Low.setText(_translate("MainWindow", "Low:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

